### ISSUE TITLE
Account repo list doesn't show private org repos

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#109]
### Description
I have access to private repos owned by Microsoft (i.e. microsoft/devhome), but they don't appear in the repo list when I select account. Searching doesn't pull it up either.

Originally opened by @cinnamon-msft

**Comment by dhoehna** [comment]
Closing as this is expected behavior for the current release of the dev home extension.

**Comment by krschau** [comment]
@dhoehna It sounds like this is a current limitation, but not exactly the design forever. Do we have an issue tracking the feature?

**Comment by dhoehna** [comment]
#192
