### ISSUE TITLE
After a reboot I'm still seeing "Connect to GitHub"

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#115]
### Steps to reproduce the bug

Description
I restarted my machine and launched "Dev Home". I saw the "Connect to GitHub" button. I clicked it and it gave a message that I was already connected. I wouldn't expect to be prompted if my account is already connected.

**Comment by vineeththomasalex** [comment]
In v0.2, this was fixed to always save credentials and restore them on restart.
