### ISSUE TITLE
Individual issues/PRs in GitHub widgets should have rounded corners

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#116]
### Steps to reproduce the bug

Description
Hovering over an individual item in a GitHub Issues widget highlights the item from side to side in the whole widget box with no padding. I would expect some left-right padding for this highlight (and also expected the individual issue items to have rounded corners).

**Comment by krschau** [comment]
Padding was added, but corners are not rounded.

**Comment by krschau** [comment]
Duplicate of https://github.com/microsoft/devhome/issues/1465
