### ISSUE TITLE
DevHome and GitHub extension both register the devhome protocol

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#118]
### Steps to reproduce the bug

Description
After authorizing the dev home GitHub app, the redirect sends you to a `devhome://` URI. Both DevHome and GitHub extension register the protocol, and Windows is asking me which one to choose. This is confusing to me as the user; I'm not sure which one should be chosen and I think I chose the wrong one the first time (DevHome seems to be blocking on this callback).

PS: You can create a Feedback Hub URI that sets the category for the user, preventing some mistakes.

**Comment by vineeththomasalex** [comment]
This was fixed since Dev Home now uses "ms-devhome" for protocol
