### ISSUE TITLE
[Reliability] Can't sign back in to GitHub extension

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#119]
### Steps to reproduce the bug

Description
Signed out through Dev Home, then clicked sign in and got the "something went wrong" error. (screenshot attached)
Also the text on the error is weird - it says to make sure my inputs are correct, but I only clicked sign in, so I don't have any inputs? Also "feedback" should have a lowercase F and we should remove the period from the second line

### Expected result

The screenshot shows that the LoginUI failure state AdaptiveCard is being displayed. This can happen if there is a failure retrieving a DeveloperIdProvider instance (under a lock) or even when the resource loader is not properly initialized. There are logging events that would indicate if we failed at retrieval of DeveloperIdProvider or if we ran into an alternate exception (for instance resource loader failure). However, the diagnostics do not contain any relevant information to Dev Home/Dev Home GitHub extension so it is hard to tell.

 

Though, the content of the failure card can be refined per suggestions in this bug. Here is a PR with proposed changes: [Change error message in adaptive card for LoginUI failure by ssparach · Pull Request microsoft/devhome#77 · microsoft/devhomegithubextension](https://github.com/microsoft/devhomegithubextension/pull/77)

@James Pike as FYI

**Comment by vineeththomasalex** [comment]
The proposed changes https://github.com/microsoft/devhomegithubextension/pull/77 were merged. There is no other actionable item for this issue since the diagnostics are unclear.
