### ISSUE TITLE
[Widgets] Authorized GitHub when adding a GitHub widget, but the add widget window did not change. It's still showing the original sign in button.

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#128]
### Steps to reproduce the bug

Description
When trying to add the Issue widget I gave authorization. When returning to the add widget window it remained unchanged. Clicking sign in opened an edge window to authorize that immediately closed itself. So in the end I'm unable to add or use the widget.

**Comment by vineeththomasalex** [comment]
This was fixed in v0.2
