### ISSUE TITLE
"Add account" has an odd "GitHub/Sign in" label

### ISSUE THREAD

**Issue by localden** [microsoft/devhomegithubextension#140]
Lots of wasted space in this view 😀 I am also not sure if this is meant to be a placeholder for more than just GitHub in the future?

![image](https://github.com/microsoft/devhome/assets/53200638/004b175e-d264-4b2d-84c8-5803f49379b5)

**Comment by krschau** [comment]
Should be coming from https://github.com/microsoft/devhomegithubextension/blob/af404f352650ba452f5c29e76226629ee6ae43aa/src/GithubPlugin/DeveloperId/LoginUIController.cs#LL109C34-L109C37

**Comment by manodasanW** [comment]
Looks like https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png from the above link never rendered.

**Comment by krschau** [comment]
@ssparach FYI. We could change this so that we save the image locally and display it in the adaptive card via base64 string. However, if there's an internet problem it's not like they can sign in with GitHub anyway.

**Comment by vineeththomasalex** [comment]
Closing this as ByDesign.
