### ISSUE TITLE
Can't add pull requests widget for organization private repo

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/devhomegithubextension#150]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add widget, pull requests, then enter the url to an organization's private repo and click the arrow

### Expected result

Adding is blocked by the organization's oauth policy, and the requests appears in the GitHub org's oauth policy page to be approved.

### Actual result

Adding is blocked by the organization's oauth policy, but there is no request to be approved so no way to unblock this.

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12700H
Physical Memory: 63.68GB (44.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by patHyatt** [comment]
How is the extension's request for approval generated? 
I do not see a OAuth app request in my organization's settings for it.

**Comment by vineeththomasalex** [comment]
The organization's settings page has an OAuth Application Policy page.
![image](https://github.com/microsoft/devhomegithubextension/assets/16733941/63c1d759-f8ac-4c61-9948-eee0857e12f1)

This shows the list of approved OAuth apps and new access requests show up here. This is only visible to the org admins.
![image](https://github.com/microsoft/devhomegithubextension/assets/16733941/fd09d1ea-f33e-4bed-b8f6-e847f868cb65)

Dev Home GitHub Extension should be granted access by the org admins. 
![image](https://github.com/microsoft/devhomegithubextension/assets/16733941/ac857eca-f225-460c-bf63-b4d9ecfa6299)

Replace _ORG_NAME_ in the link here to navigate directly to the OAuth App settings page. https://github.com/organizations/_ORG_NAME_/settings/oauth_application_policy


If you are an org admin, and this does not show up in your Org settings page, that is unexpected. It might be a GitHub.com problem. However, please re-open this issue in that case to keep track of it.

**Comment by krschau** [comment]
I started an FAQ page and added the info here: https://github.com/microsoft/devhomegithubextension/wiki/FAQ#how-do-i-access-my-organizations-private-repo
