### ISSUE TITLE
GitHub Issue widget isn't making any updates when something changed in repo

### ISSUE THREAD

**Issue by Ishaan1106** [microsoft/devhomegithubextension#221]
### Dev Home version

0.401.226.0

### Windows build number

10.0.23536.1000

### Other software

OS Build Version: 10.0.23536.1000.amd64fre.ni_prerelease.230826-1546
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

I added a "GitHub repo issue" widget which shows all the opened issues.
but when the issue was closed its still showing that issue as open which is making it look more messy.

### Expected result

When an issue is closed in a GitHub repo the widget should be showing that issue as closed or either removing it from that list 

### Actual result

when the issue was closed the widget is still showing that issue as open 

### Included System Information

Physical Memory: 7.34GB (2.78GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe

**Comment by dkbennett** [comment]
This is a good bug, found the root cause. It's also affecting Pull Requests. I'll have this fixed soon.

**Comment by Ishaan1106** [comment]
> This is a good bug, found the root cause. It's also affecting Pull Requests. I'll have this fixed soon.
@dkbennett can you please explain me the root cause of the problem and the solution ? it will be helpful
