### ISSUE TITLE
Extension requires too much OAuth permissions

### ISSUE THREAD

**Issue by sylveon** [microsoft/devhomegithubextension#235]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

N/A

### Steps to reproduce the bug

1. Link your GitHub account to Dev Home

### Expected result

I did not expect the extension to ask for full access to personal user data, which includes private email address, private profile information, followers, as well as the ability to edit my profile.

### Actual result

![image](https://github.com/microsoft/devhomegithubextension/assets/6440374/5fd2aa6a-45a3-43a1-a72d-364f62756b6f)

**Comment by vineeththomasalex** [comment]
Thanks for the issue. This will be addressed in a future release.
