### ISSUE TITLE
REMOVE THIS OFF MY COMPUTER RIGHT NOW

### ISSUE THREAD

**Issue by LandonBoi123** [microsoft/devhomegithubextension#237]
### Other software

I updated Windows, and this piece of crap installed to my computer, so many people are mad, we would be happy if we could uninstall it, but no... MORE BLOATWARE!

### Steps to reproduce the bug

updating windows...

### Expected result

it installs itself

### Actual result

it installs itself

**Comment by krschau** [comment]
As Dev Home 0.5, this GitHub Extension is not automatically installed by Dev Home or the OS. If you have this extension installed and would like to remove it, you may uninstall it via the Apps > Installed apps page in Windows Settings.
