### ISSUE TITLE
Unable to Launch Browser for GitHub Login 

### ISSUE THREAD

**Issue by KelvinEuclides** [microsoft/devhomegithubextension#250]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.0

### Other software

Edg/118.0.2088.46

### Steps to reproduce the bug

Dev Home -> Settings -> Add Account -> Sign in to GitHub

### Expected result

Extension Should open the default browser in the background or create a new tab or GitHub authentication in

### Actual result

Extension Does not open the default browser or create a new tab create

### Included System Information

System Manufacturer	Dell Inc.	
System Model	Inspiron 5502	
System Type	x64-based PC	
System SKU	0A02	
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 1690 Mhz, 4 Core(s), 8 Logical Processor(s)	
BIOS Version/Date	Dell Inc. 1.25.0, 10/08/2023	
SMBIOS Version	3.2	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	Dell Inc.	
BaseBoard Product	0W3XW5	
BaseBoard Version	A00	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\WINDOWS	
System Directory	C:\WINDOWS\system32	
Boot Device	\Device\HarddiskVolume2	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.22621.1413"	
User Name	KELVIN-PC\kelvi	
Time Zone	South Africa Standard Time	
Installed Physical Memory (RAM)	16,0 GB	
Total Physical Memory	15,7 GB	
Available Physical Memory	5,36 GB	
Total Virtual Memory	20,0 GB	
Available Virtual Memory	5,36 GB	
Page File Space	4,25 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	On	
Virtualization-based security	Running	
Virtualization-based security Required Security Properties

**Comment by vineeththomasalex** [comment]
@KelvinEuclides Does this occur repeatedly, or only the first time the "Connect your account" message box is opened?

**Comment by KelvinEuclides** [comment]
It happens repeatedly

**Comment by vineeththomasalex** [comment]
This might be a duplicate of https://github.com/microsoft/devhomegithubextension/issues/108 . But this shouldn't happen repeatedly. Will need logs. 

It would be helpful for us if you could share your Dev Home logs. These logs can be found at %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState and %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\TempState. You can share these folders via a OneDrive link or zip them and attach them to a comment here. If you share this way, you may want to look through the logs in case there are any details included that you would like to remove (for example, private repo names). Alternatively, you can open a Feedback Hub issue and attach them there. If you use Feedback Hub, please paste the URL at the bottom of the report here so we can easily find it.

**Comment by vineeththomasalex** [comment]
Closing as duplicate of #108 based on behavior and lack of logs to prove otherwise.
