### ISSUE TITLE
Issues widget shows issues in reverse order

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhomegithubextension#278]
### Dev Home version

0.701.318.0

### Other software

GitHub extension version 0.700.318.0

### Steps to reproduce the bug

Pin a GitHub issues widget

### Expected result

Issues should appear in order of most recently updated

### Actual result

Issues are appearing in reverse order, so most recently updated gets added to the bottom:
![image](https://github.com/microsoft/devhomegithubextension/assets/48369326/4b2dbaab-3841-4666-98cf-56fc0fda7a2d)

**Comment by crutkas** [comment]
in .700.323 i cannot repro this.  I tried devhome and powertoys repo

![image](https://github.com/microsoft/devhomegithubextension/assets/1462282/ac2cf2d7-7bc5-42d2-a601-5dbaafb7dcdf)

**Comment by krschau** [comment]
@cinnamon-msft to try to repro today, and if not, close the issue.

**Comment by cinnamon-msft** [comment]
Not seeing this anymore, closing this out :)

**Comment by cinnamon-msft** [comment]
Seeing this again, but what's interesting is the top half of my issues are in order, then at some point newer issues are appended to the bottom of the widget in reverse order.

Here are my installed versions:
Dev Home (Preview): 0.801.344.0
Dev Home GitHub Extension (Preview): 0.800.344.0

![image](https://github.com/microsoft/devhomegithubextension/assets/48369326/3428a117-22e6-4f9a-854f-18da37d09800)

![image](https://github.com/microsoft/devhomegithubextension/assets/48369326/fe21bcb1-e485-4b7f-913e-a2542d72515f)
