### ISSUE TITLE
GitHub Login

### ISSUE THREAD

**Issue by dithnim** [microsoft/devhomegithubextension#283]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

When I tried to log into my GitHub account using GitHub extension, it didn't work.

### Expected result

I expected a login page to enter my GitHub ID and password to log in.

### Actual result

Sign in button did not work.

### Included System Information

Physical Memory: 9.87GB (4.07GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by KuroChu** [comment]
Try going to Settings>Apps>Installed Apps>Dev Home and click on advanced options to then repair the program which should help with opening the login page

**Comment by vineeththomasalex** [comment]
@dithnim Does closing and reopening the Signin popup fix this? This might be a duplicate of #108

**Comment by vineeththomasalex** [comment]
It would be helpful for us if you could share your Dev Home logs. These logs can be found at %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState and %LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\TempState. You can share these folders via a OneDrive link or zip them and attach them to a comment here. If you share this way, you may want to look through the logs in case there are any details included that you would like to remove (for example, private repo names). Alternatively, you can open a Feedback Hub issue and attach them there. If you use Feedback Hub, please paste the URL at the bottom of the report here so we can easily find it.

**Comment by vineeththomasalex** [comment]
Based on the description and absence of logs, closing this as a duplicate of #108
