### ISSUE TITLE
Complete app crash on cloning private repository

### ISSUE THREAD

**Issue by KuroChu** [microsoft/devhomegithubextension#285]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

Log in to an github account with an organisation but don't grant right to it. Then try to clone a private repository from it

### Expected result

There are no current expected results except some kind of warning

### Actual result

App just completely crashes without any warning.

### Included System Information

Os version: 22H2 (0S Build 22621.2715)

**Comment by dhoehna** [comment]
Hello,

Thank you for filing this bug.  Any chance you could paste the github URL so I can test with it?

**Comment by dhoehna** [comment]
Hi @KuroChu . It would be helpful for us if you could share your Dev Home logs. 
              These logs can be found at 
              `%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState` and 
              `%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\TempState`. 
              You can share these folders via a OneDrive link or zip them and attach them to a 
              comment here. If you share this way, you may want to look through the logs in case 
              there are any details included that you would like to remove (for example, private 
              repo names). Alternatively, you can open a Feedback Hub issue and attach them there. 
              If you use Feedback Hub, please paste the URL at the bottom of the report here so we 
              can easily find it.

**Comment by dhoehna** [comment]
The older version of DevHome and the github extension does have this crash.  Can you please upgrade both DevHome and the github extension to version 0.7?
