### ISSUE TITLE
Prevent user from signing into Enterprise account if they are already signed in with a non-Enterprise one

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhomegithubextension#335]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.19045.0

### Steps to reproduce the bug

1. On Dev Home, with a non-Enterprise GitHub account already connected, navigate to Settings -> Accounts -> Add Account, choose GitHub, and pick the Sign in to GitHub Enterprise Server option. 

### Expected result

I believe side-by-side accounts are not yet supported, so the extension should tell me this. 

### Actual result

The extension tells me to file feedback.

![image](https://github.com/microsoft/devhomegithubextension/assets/8368026/4a5a3f97-1c4d-41cb-a355-9283fc01a798)

**Comment by vineeththomasalex** [comment]
This is correct. Hoiwever, the message will go away in the next release when multi-user/side-by-side will be supported. Marking this as Wont-fix.
