### ISSUE TITLE
GitHub issues order is inconsistent/wrong

### ISSUE THREAD

**Issue by timdeschryver** [microsoft/devhomegithubextension#338]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.0

### Steps to reproduce the bug

1. Add a new GitHub issues widget and add a GitHub repo that contains many issues (I think this issue starts to occur when the issues are paged). For example, use https://github.com/microsoft/devhome/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3AIssue-Feature as source.

![image](https://github.com/microsoft/devhome/assets/28659384/f5468c4f-2683-4613-ab17-104ff7bff985)

2. Confirm the widget

3. Wait until the issues are loaded

### Expected result

I expect the order to be consistent with the GitHub issues page.
Also note the explicit order within the query `issue+sort%3Acreated-desc` is also not applied.

### Actual result

The applied order is wrong.

DevHome:

![image](https://github.com/microsoft/devhome/assets/28659384/8190a6f4-b389-4d09-80f2-156386b6d92a)

GitHub:

![image](https://github.com/microsoft/devhome/assets/28659384/214bbb98-cec7-473d-9510-d7e761e46b11)

If I scroll down within the widget the difference is clearly visible:
![image](https://github.com/microsoft/devhome/assets/28659384/b5beb781-a6b5-4a0d-ba22-e82c26b4a236)

**Comment by timdeschryver** [comment]
@krschau I'm on v0.1000.393.0.
I just tried it again, and it seems like this is still an issue.

![image](https://github.com/microsoft/devhomegithubextension/assets/28659384/432b48cf-28fb-4e17-aeac-9d8da8f3b668)


My machine is configured as (I don't know if this matters):
- Region: Belgium
- Regional format: Dutch (Belgium) - meaning that dates are formatted as dd/MM/yyyy

**Comment by dkbennett** [comment]
I do not see this when I attempt repro, but this issue looks exactly like the bug I just fixed where stale data in the datastore was not cleaned out and was corrupting the view. Can you please submit logs? I suspect the data may not be updating.

**Comment by dkbennett** [comment]
Our /logs command has a bug being fixed, manually copying the post here:

             These logs can be found at 
              `%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState` and 
              `%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\TempState`. 
              You can share these folders via a OneDrive link or zip them and attach them to a 
              comment here. If you share this way, you may want to look through the logs in case 
              there are any details included that you would like to remove (for example, private 
              repo names). Alternatively, you can open a Feedback Hub issue and attach them there. 
              If you use Feedback Hub, please paste the URL at the bottom of the report here so we 
              can easily find it.

**Comment by timdeschryver** [comment]
Attached to this comment are my logs.
Before creating them I removed all widgets, cleaned the logs, then restarted DevHome and added the GitHub issue widget to my dashboard.

[Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe.zip](https://github.com/microsoft/devhomegithubextension/files/142
[Microsoft.Windows.DevHome_8wekyb3d8bbwe.zip](https://github.com/microsoft/devhomegithubextension/files/14201928/Microsoft.Windows.DevHome_8wekyb3d8bbwe.zip)
01926/Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe.zip)

**Comment by dkbennett** [comment]
Thank you, there was nothing unusual in the logs, so I suspect there is some database corruption that was not healed by my fix, and I would need the datastore to troubleshoot further. That could also be submitted but may have other information in it you don't want publicly visible, so if you are comfortable with it, please open a Feedback Hub issue, attach the datastore located at 

`%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe\LocalState\GitHubData.db`

And paste the url at the bottom of the report here.

**Comment by timdeschryver** [comment]
@dkbennett it seems like this issue is resolved after I deleted the `GitHubData.db` file.

**Comment by dkbennett** [comment]
Ok good that it's resolved, but hopefully there isn't a migration bug from old state to new state.  The corruption happened over time, so please reactivate this issue if you experience it again, thank you for the info!
