### ISSUE TITLE
Several dashboard widgets blank, account and extension missing?

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhomegithubextension#348]
### Dev Home version

0.401.212.0

### Windows build number

10.0.23518.1000

### Other software

OS Build Version: 10.0.23518.1000.amd64fre.ni_moment_directadept.230731-1436
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

1. Configure and pin several Issue and Pull Request widgets to the Dashboard. 
2. Close the application and come back to it some indeterminate amount of time later (in my case probably on the order of a few days) with device reboots, etc. in between the two sessions.

### Expected result

Dashboard is configured exactly as it was before.

### Actual result

When I launched the app just now, I see that the only 1 of the 8 widgets is displaying any data (the others appear as though they are waiting to be configured). 

![image](https://github.com/microsoft/devhome/assets/8368026/54b2dcfc-c152-4e73-88e1-8054e0d58df3)

I checked the Accounts and my GitHub identity is no longer showing up there. When I try to click to add an account, the app tells me that I have no extensions installed (though I see it installed and it's enabled in the UI). 

(I know that the additional Preview entries are due to microsoft/devhome#1286 ; FWIW, I tried disabling those, closing the app, and relaunching, but the behavior was the same.)

![image](https://github.com/microsoft/devhome/assets/8368026/2caa289d-ecc3-452a-aee1-fcb4fd1ccf81)

![image](https://github.com/microsoft/devhome/assets/8368026/98be0d0e-dbcc-4dc9-93dd-958b4c605f80)

### Included System Information

Physical Memory: 31.83GB (17.68GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.300.186.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.212.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
I haven't seen this in a long time, and we have made enhancements in the area, so closing.
