### ISSUE TITLE
File name GitHubSearchManger.cs should be GitHubSearchManager.cs

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/devhomegithubextension#402]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22621.2506

### Steps to reproduce the bug

Check the following file name:
src> GitHubExtension > DataManager > GitHubSearchManger.cs

### Expected result

The file name should be:
GitHubSearchManager.cs

### Actual result

The current file name is:
GitHubSearchManger.cs

**Comment by krschau** [comment]
Nice find!
